<div style="
    background-image: url('https://miro.medium.com/v2/resize:fit:1000/1*RY96IbeNH41iTggMlfjI4A.jpeg');
    background-size: cover;
    background-position: center;
    height: 380px;
    width: 100%;
    display: flex;
    align-items: center;
    padding-left: 20px;  
    color: white;
    border-radius: 10px;">
    
<span style="font-weight: bold; font-size: 30px;">🎯 3. NumPy Giriş</span>

</div>


## 3.1 NumPy nedir?
- Sayısal hesaplama için **çok boyutlu** dizileri destekleyen bir kütüphane.

- **NumPy (Numerical Python)** Python'da bilimsel hesaplamalar için bir kütüphanedir.

- Temel veri yapısı, **çok boyutlu** dizileri temsil eden ndarray'dir (N boyutlu dizi).

- **NumPy**, Python listelerinden **daha hızlı** ve daha **bellek verimlidir**.

NumPy, Python paket yöneticisi pip ile kurulabilir:

    pip install numpy

## 3.2 NumPy Dizileri Oluşturma

In [ ]:
import numpy as np

# 1D dizi (vektör)
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)  # [1 2 3 4 5]

# 2D dizi (matris)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
# [[1 2 3]
#  [4 5 6]]

# 3D dizi
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)
# [[[1 2]
#   [3 4]]
#
#  [[5 6]
#   [7 8]]]

## 3.3 Özel Diziler Oluşturma

NumPy, özel diziler oluşturmak için çeşitli işlevler sağlar:

- **np.zeros():** Tüm öğeleri 0 olan dizi.

- **np.ones():** Tüm öğeleri içeren dizi 1.

- **np.full():** Tüm öğeleri belirli bir değerle doldurur.

- **np.eye():** Birim matrisi (birim matris).

- **np.arange():** Belirli bir aralıktaki sayıları içeren dizi.

- **np.linspace():** Belirli bir aralıktaki eşit aralıklı sayıların dizisi.

In [ ]:
# zeros()
zeros_arr = np.zeros((2, 3)) # A 2x3 matris
print(zeros_arr)
# [[0. 0. 0.]
# [0. 0. 0.]]

# ones()
ones_arr = np.ones((3, 2)) # A 3x2 matris
print(ones_arr)
# [[1. 1.]
# [1. 1.]
# [1. 1.]]

# full()
full_arr = np.full((2, 2), 7) # 2x2 matris, tüm elemanlar 7
print(full_arr)
# [[7 7]
# [7 7]]

# eye()
identity_matrix = np.eye(3) # 3x3 birim matris
print(identity_matrix)
# [[1. 0. 0.]
# [0. 1. 0.]
# [0. 0. 1.]]

# arange()
range_arr = np.arange(0, 10, 2) # 2 adımlarla 0'dan 10'a
print(range_arr) # [0 2 4 6 8]

# linspace()
linspace_arr = np.linspace(0, 1, 5) # 0 ile 1 arasında 5 eşit parçaya bölünmüş dizi
print(linspace_arr) # [0. 0.25 0.5 0.75 1. ]

## 3.4 Dizi Nitelikleri

NumPy dizileri hakkında bilgi almak için çeşitli özellikler kullanılır:

- **shape:** Dizinin boyutlarını verir.

- **ndim:** Dizinin boyut sayısını verir.

- **size:** Dizideki toplam eleman sayısı verir.

- **dtype:** Dizinin veri tipini verir.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape) # (2, 3) (2 satır, 3 sütun)
print(arr.ndim) # 2 (2D)
print(arr.size) # 6 (toplam eleman sayısı)
print(arr.dtype) # int64 (veri tipi)

## 3.5 Dizi İşlemleri

**reshape():** Dizinin boyutlarını değiştirir.

In [ ]:
arr = np.arange(1, 7) # [1 2 3 4 5 6]
reshaped_arr = arr.reshape(2, 3) # 2x3 matris
print(reshaped_arr)
# [[1 2 3]
# [4 5 6]]

## 3.6 Dizi Birleştirme
**np.concatenate():** Dizileri birleştirir.

**np.vstack():** Dizileri dikey olarak birleştirin.

**np.hstack():** Dizileri yatay olarak birleştirir.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# concatenate()
combined = np.concatenate((arr1, arr2), axis=0)  # Dikey Birleştirme
print(combined)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# concatenate()
combined = np.concatenate((arr1, arr2), axis=1)  # Yatay Birleştirme
print(combined)
# [[1 2 5 6]
#  [3 4 7 8]]

# vstack()
vstacked = np.vstack((arr1, arr2))
print(vstacked)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# hstack()
hstacked = np.hstack((arr1, arr2))
print(hstacked)
# [[1 2 5 6]
#  [3 4 7 8]]

## 3.7 Matematiksel İşlemler
- NumPy dizilerde hızlı matematiksel işlemlere olanak sağlar:

    - Toplama, Çıkarma, Çarpma, Bölme: Element element işlemleri.

        - **np.sum():** Dizinin toplamını hesaplar.

        - **np.mean():** Dizinin ortalamasını hesaplar.

        - **np.min()**, **np.max():** Dizinin minimum ve maksimum değerlerini bulur.

        - **np.std():** Dizinin standard sapmasını hesaplar.

In [ ]:
arr = np.array([1, 2, 3, 4])

# Eleman bazında işlemler
print(arr + 2) # [3 4 5 6]
print(arr * 2) # [2 4 6 8]

# Dizi toplamı
print(np.sum(arr)) # 10

# Dizi ortalaması
print(np.mean(arr)) # 2.5

# Dizi maksimum ve minimum değerleri
print(np.min(arr)) # 1
print(np.max(arr)) # 4

# Dizi standard sapması
print(np.std(arr))

## 3.8 İndeksleme ve Dilimleme

### 3.8.1 İndeksleme
NumPy dizilerinde indeksleme Python listelerine benzer şekilde çalışır.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Tek bir öğeye erişim
print(arr[0]) # 1

# Negatif indeksleme (sondan başlayarak)
print(arr[-1]) # 5

### 3.8.2 Dilimleme
Dilimleme, dizinin belirli bir bölümünü elde etmek için kullanılır.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Belirli bir aralık
print(arr[1:4]) # [2 3 4]

# Belirli bir aralık ve adım sayısı
print(arr[::2]) # [1 3 5]

## 3.9 Matrix Product

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matris çarpımı
result = np.dot(A, B)
print(result)
# [[19 22]
#  [43 50]]

## 3.Alıştırmalar
1. 1'den 10'a kadar sayıları içeren bir NumPy dizisi oluşturun.

2. Bu diziyi 2x5'lik bir matrise dönüştürün.

3. Matrisin devriğini alın.

4. İki matrisin çarpımını hesaplayın.

5. Bir dizinin ortalamasını ve standart sapmasını hesaplayın.

Daha fazla bilgi için [NumPy dokümantasyonuna](https://numpy.org/doc/stable/reference/#)
göz atabilirsiniz.